# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aeb36a118f7df8a9ce8aed9b253296904c60707bff0e70c08c4de40148b8ce3bbfd6e7edab9fcd0c6de2040d0737224b7a1953c6966dbdfab9a2e3826cd2945c

test:
  secret_key_base: dbc68f6e0ddfe5744258cc8f1c7ca588b78feacbece68ae46d59e064467c6582f34689e1ca3dade59993b0c44bf8546ac9e382b0d899f9a840792dc7a0d1b8be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
